# Ref:
#   - https://github.com/sonnym/travis-ci-drupal-module-example/blob/master/.travis.yml
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  # - hhvm

# matrix:
#   allow_failures:
#     - php: hhvm

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # ---------------------
  # Install Drush
  # ---------------------
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:dev-master

  # ---------------------
  # Setup DB
  # ---------------------
  - mysql -e 'create database drupal;'

before_script:
  # ---------------------
  # Variables
  # ---------------------
  - cd ..
  - export VENDOR=`pwd`
  - cd ..
  - export DRUPAL=`pwd`'/drupal/'

  # ---------------------
  # Download the codebase
  # ---------------------
  - wget https://github.com/atdrupal/atest_profile/archive/v7.3.zip
  - unzip -qq v7.3.zip
  - mv atest_profile-7.3 $DRUPAL
  - cd $DRUPAL
  - drush si testing --db-url=mysql://root:@localhost/drupal --yes
  - mv $VENDOR/* sites/all/modules/

  # ---------------------
  # Prepare env for the module
  # ---------------------
  - drush vset --yes file_temporary_path /tmp
  - drush en -y composer_manager simpletest at_base atest_base

  # ---------------------
  # No cache data
  # ---------------------
  - drush cc all

script:
  - drush test-run --dirty --field-labels=0 'AT Unit'
  - drush test-run --dirty --field-labels=0 'AT Web'
