language: php
php:
  - 5.3
  - 5.4
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # ---------------------
  # Install Drush
  # ---------------------
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:dev-master

  # ---------------------
  # Setup DB
  # ---------------------
  - mysql -e 'create database drupal;'

before_script:
  # ---------------------
  # Variables
  # ---------------------
  - cd ..
  - export VENDOR=`pwd`
  - cd ..
  - export DRUPAL=`pwd`'/drupal/'

  # ---------------------
  # Download the codebase
  # ---------------------
  - wget https://github.com/andytruong/atest_profile/archive/master.zip
  - unzip -qq master
  - mv atest_profile-master $DRUPAL
  - cd $DRUPAL
  - drush si testing --db-url=mysql://root:@localhost/drupal --yes
  - mv $VENDOR/* sites/all/modules/

  # ---------------------
  # Prepare env for the module
  # ---------------------
  - drush vset --yes file_temporary_path /tmp
  - drush en -y simpletest at_base atest_base

  # ---------------------
  # No cache data
  # ---------------------
  - drush cc all

script:
  - drush test-run --dirty --field-labels=0 'AT Unit'
  - drush test-run --dirty --field-labels=0 'AT Web'

notifications:
  email: false
  hipchat: 76d833fa0b6bae8860f279a0e7dba0@me.Andy
  flowdock: 8e80a6538fa73fda0f7dd60bf2d44356
