language: php
php:
  - 5.3
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
 - export DRUPAL=`pwd`'/drupal/'
 - export PHP=`which php`
 - curl -sS https://gist.github.com/andytruong/677b2ad8e907d9e6832c/raw/travis.bash | bash
 - drush en -y simpletest at_base
 - drush at_require at_base
 - drush cc all
 - sleep 3

script: drush test-run 'AT Base'
