# Ref:
#   - https://github.com/sonnym/travis-ci-drupal-module-example/blob/master/.travis.yml
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  # - hhvm

# matrix:
#   allow_failures:
#     - php: hhvm

mysql:
  database: drupal
  username: root
  encoding: utf8

  # ---------------------
  # Setup DB
  # ---------------------
  - mysql -e 'create database drupal;'

before_script:
  # ---------------------
  # Install Drush
  # ---------------------
  - wget https://github.com/drush-ops/drush/archive/5.10.0.tar.gz
  - tar zxf 5.10.0.tar.gz
  - mv drush-5.10.0/ ~/drush
  - alias drush="~/drush/drush"

  # ---------------------
  # Variables
  # ---------------------
  - cd ..
  - export VENDOR=`pwd`
  - cd ..
  - export DRUPAL=`pwd`'/drupal/'

  # ---------------------
  # Download the codebase
  # ---------------------
  - wget https://github.com/andytruong/atest_profile/archive/master.zip
  - unzip -qq master
  - mv atest_profile-master $DRUPAL
  - cd $DRUPAL
  - drush si testing --db-url=mysql://root:@localhost/drupal --yes
  - mv $VENDOR/* sites/all/modules/

  # ---------------------
  # Prepare env for the module
  # ---------------------
  - drush vset --yes file_temporary_path /tmp
  - drush en -y simpletest at_base atest_base

  # ---------------------
  # No cache data
  # ---------------------
  - drush cc all

script:
  - drush test-run --dirty 'AT Unit'
  - drush test-run --dirty 'AT Web'
