projects:
  spyc:
    type: library
    download:
      type: git
      url: https://github.com/mustangostang/spyc.git
      branch: 0.5.1
  pimple:
    type: library
    download:
      type: git
      url: https://github.com/fabpot/Pimple.git
      revision: v1.1.0
