projects:
  spyc:
    type: library
    download:
      type: git
      url: 'https://github.com/mustangostang/spyc.git'
      branch: '0.5.1'

  pimple:
    type: library
    download:
      type: git
      url: 'https://github.com/fabpot/Pimple.git'
      branch: 'v2.0.0'

  twig:
    type: library
    download:
      type: git
      url: 'https://github.com/fabpot/Twig.git'
      branch: 'v1.15.1'

  expression_language:
    type: library
    download:
      type: git
      url: 'https://github.com/symfony/expression-language.git'
      branch: 'v2.4.1'

  fontawesome:
    type: library
    download:
      type: file
      url: 'http://fortawesome.github.io/Font-Awesome/assets/font-awesome-4.0.3.zip'

  fontello:
    type: library
    download:
      type: file
      url: https://github.com/fontello/fontello/archive/5.1.0.tar.gz
