projects:
  # spyc:
  #   type: library
  #   download:
  #     type: git
  #     url: https://github.com/mustangostang/spyc.git
  #     branch: 0.5.1
  pimple:
    type: library
    download:
      type: git
      url: https://github.com/fabpot/Pimple.git
      revision: dc03a407f20cbd4eaf55472875ad47ee96d921ea
  twig:
    type: library
    download:
      type: git
      url: https://github.com/fabpot/Twig.git
      branch: v1.15.0
