projects:
  fontawesome:
    type: library
    download:
      type: file
      url: 'http://fortawesome.github.io/Font-Awesome/assets/font-awesome-4.0.3.zip'

  fontello:
    type: library
    download:
      type: git
      url: https://github.com/fontello/fontello.git
      branch: '5.1.0'
    options:
      working-copy: true
