services:
  twig.core:
    class: 'Twig_Environment'
    factory_class: 'Drupal\at_base\Twig\EnvironmentFactory'
    factory_method: getObject

  twig.file_loader:
    class: 'Twig_Loader_Filesystem'
    factory_class: 'Drupal\at_base\Twig\EnvironmentFactory'
    factory_method: getFileLoader

  twig.string_loader:
    class: 'Twig_Loader_String'

  twig:
    class: 'Twig_Environment'
    factory_class: 'Drupal\at_base\Twig\EnvironmentFactory'
    factory_method: getFileService
    arguments: ['@twig.core']
    calls:
      - ['setLoader', ['@twig.file_loader']]

  twig_string:
    class: 'Twig_Environment'
    factory_class: 'Drupal\at_base\Twig\EnvironmentFactory'
    factory_method: getStringService
    arguments: ['@twig.core']
    calls:
      - ['setLoader', ['@twig.string_loader']]
