services:
  cache.tag_discover:
    class: 'Drupal\at_base\Cache\Warming\TagDiscover'

  # ---------------------
  # Warmers
  # ---------------------
#  cache.warmer:
#    class: 'Drupal\at_base\Cache\Warming\Warmer'
#    arguments: ['@cache.tag_discover', '@cache.tag_flusher']
#
#  cache.warmer.simple:
#    class: 'Drupal\at_base\Cache\Warming\Warmer\SimpleWarmer'
#    tags:
#      - { name: 'cache.warmer', weight: 100 }
#
#  cache.warmer.entity:
#    class: 'Drupal\at_base\Cache\Warming\Warmer\EntityWarmer'
#    tags:
#      - { name: 'cache.warmer' }
#
#  cache.warmer.view:
#    class: 'Drupal\at_base\Cache\Warming\Warmer\ViewWarmer'
#    tags:
#      - { name: 'cache.warmer' }
