imports:
  - { resource: services.kv.yml }
  - { resource: services.cache.yml }
  - { resource: services.theming.yml }
  - { resource: services.helper.yml }
  - { resource: services.icon.yml }

services:
  expression_language:
    class: 'Symfony\Component\ExpressionLanguage\ExpressionLanguage'

# 'wrapper.db' => return at()->getApi()->getDrupalDatabaseAPI() ,
# 'wrapper.cache' => return at()->getApi()->getDrupalCacheAPI();
# 'config' => return new Config(new Config_Resolver());
# 'helper.config_fetcher' => return new ConfigFetcher();
