services:

  helper.controller.resolver:
    class: '\Drupal\at_base\Helper\Controller_Resolver'

  helper.content_render:
    reuse: false
    class: 'Drupal\at_base\Helper\ContentRender'

  helper.real_path:
    class: 'Drupal\at_base\Helper\Real_Path'

  helper.timer:
    class: 'Drupal\at_base\Helper\Timer'
