services:

  helper.controller.resolver:
    class: '\Drupal\at_base\Helper\ControllerResolver'

  helper.ContentRender:
    reuse: false
    class: 'Drupal\at_base\Helper\ContentRender'

  helper.real_path:
    class: 'Drupal\at_base\Helper\RealPath'

  helper.timer:
    class: 'Drupal\at_base\Helper\Timer'
