imports:
  - { resource: services.cache.yml }
  - { resource: services.theming.yml }
  - { resource: services.helper.yml }

services:
  class_loader:
    class: 'Doctrine\Common\ClassLoader'
    file: '%doctrine_common/lib/Doctrine/Common/ClassLoader.php'

  expression_language:
    class: 'Symfony\Component\ExpressionLanguage\ExpressionLanguage'
    factory_class: 'AT'
    factory_method: getExpressionLanguage
