services:

  helper.controller.resolver:
    class: 'AndyTruong\Common\ControllerResolver'

  helper.content_render:
    reuse: false
    class: 'Drupal\at_base\Helper\ContentRender'

  helper.real_path:
    class: 'Drupal\at_base\Helper\RealPath'

  helper.timer:
    class: 'Drupal\at_base\Helper\Timer'
