services:
  cache.tag_flusher:
    class: 'Drupal\at_base\Cache\Warming\Tag_Flusher'

  cache.tag_discover:
    class: 'Drupal\at_base\Cache\Warming\Tag_Discover'

  cache.warmer:
    class: 'Drupal\at_base\Cache\Warming\Warmer'
    arguments: ['@cache.tag_discover', '@cache.tag_flusher']

  cache.warmer.simple:
    class: 'Drupal\at_base\Cache\Warming\Warmer\Simple_Warmer'
    tags:
      - { name: 'cache.warmer', weight: 100 }

  cache.warmer.entity:
    class: 'Drupal\at_base\Cache\Warming\Warmer\Entity_Warmer'
    tags:
      - { name: 'cache.warmer' }

  cache.warmer.view:
    class: 'Drupal\at_base\Cache\Warming\Warmer\View_Warmer'
    tags:
      - { name: 'cache.warmer' }

  # ---------------------
  # Warmers > Entity > Relationship
  # ---------------------
  cache.warmer.entity.relationship.file:
    class: 'Drupal\at_base\Cache\Warming\Warmer\Entity_Warmer\Relationship\File_Warmer'
    tags:
      - { name: 'cache.warmer.entity.relationships' }

  cache.warmer.entity.relationship.user:
    class: 'Drupal\at_base\Cache\Warming\Warmer\Entity_Warmer\Relationship\User_Warmer'
    tags:
      - { name: 'cache.warmer.entity.relationships' }

  cache.warmer.entity.relationship.taxonomy-term:
    class: 'Drupal\at_base\Cache\Warming\Warmer\Entity_Warmer\Relationship\Taxonomy_Term_Warmer'
    tags:
      - { name: 'cache.warmer.entity.relationships' }

  cache.warmer.entity.relationship.entity_reference:
    class: 'Drupal\at_base\Cache\Warming\Warmer\Entity_Warmer\Relationship\Entity_Reference_Warmer'
    tags:
      - { name: 'cache.warmer.entity.relationships' }

  cache.warmer.entity.relationship.relation:
    class: 'Drupal\at_base\Cache\Warming\Warmer\Entity_Warmer\Relationship\Relation_Warmer'
    tags:
      - { name: 'cache.warmer.entity.relationships' }
