services:
  type.any:
    class: Drupal\at_base\TypedData\DataTypes\Any
    reuse: false
  type.boolean:
    class: Drupal\at_base\TypedData\DataTypes\Boolean
    reuse: false
  type.integer:
    class: Drupal\at_base\TypedData\DataTypes\Integer
    reuse: false
  type.string:
    class: Drupal\at_base\TypedData\DataTypes\String
    reuse: false
  type.function:
    class: Drupal\at_base\TypedData\DataTypes\Function
    reuse: false
  type.constant:
    class: Drupal\at_base\TypedData\DataTypes\Constant
    reuse: false
  type.mapping:
    class: Drupal\at_base\TypedData\DataTypes\Mapping
    reuse: false
