services:
  twig:
    class: '\Twig_Environment'
    factory_class: '\Drupal\at_base\Twig\Environment_Factory'
    factory_method: getService
  twig_string:
    class: '\Twig_Environment'
    factory_class: '\Drupal\at_base\Twig\Environment_Factory'
    factory_method: getStringService
    arguments: ['@twig']
