imports:
  - { resource: services.cache.yml }
  - { resource: services.theming.yml }
  - { resource: services.helper.yml }

services:
  # ---------------------
  # Config
  # ---------------------
  expression_language:
    class: 'Symfony\Component\ExpressionLanguage\ExpressionLanguage'
    factory_class: 'AT'
    factory_method: getExpressionLanguage
