services:
  type.any:
    class: Drupal\at_base\TypedData\DataTypes\Any
    scope: prototype
  type.boolean:
    class: Drupal\at_base\TypedData\DataTypes\Boolean
    scope: prototype
  type.integer:
    class: Drupal\at_base\TypedData\DataTypes\Integer
    scope: prototype
  type.string:
    class: Drupal\at_base\TypedData\DataTypes\String
    scope: prototype
  type.callable:
    class: Drupal\at_base\TypedData\DataTypes\Kallable
    scope: prototype
  type.function:
    class: Drupal\at_base\TypedData\DataTypes\Fn
    scope: prototype
  type.constant:
    class: Drupal\at_base\TypedData\DataTypes\Constant
    scope: prototype
  type.list:
    class: Drupal\at_base\TypedData\DataTypes\ItemList
    scope: prototype
  type.mapping:
    class: Drupal\at_base\TypedData\DataTypes\Mapping
    scope: prototype
