twig_filters:
  # ---------------------
  # Core
  # ---------------------
  render: render

  # Example: {{ 'Drupal'|t }}
  t: t

  # Example: {{ 'user/1'|url }}
  url: url

  # Example: {{ 'This is my string'|_filter_autop }}
  _filter_autop: _filter_autop

  # Example: {{ 'system:powered-by'|drupalBlock }}
  __drupalBlock: [\Drupal\at_base\Twig\Filters\Block, render]

  # Example: {{ 'user:1'|drupalEntity }}
  __drupalEntity: [\Drupal\at_base\Twig\Filters\Entity, render]

  # Examples:
  #   {{ 'viewName'|drupalView }}
  #   {{ 'viewName'|drupalView('default') }}
  #   {{ 'viewName'|drupalView('default', arg1, arg2, arg3) }}
  #   {{ 'viewName'|drupalView({template: '@at_base/templates/views_view.html.twig'}) }}
  #   {{ 'viewName'|drupalView({template: '...', display_id: 'default', arguments: [arg1, arg2, arg3]}) }}
  drupalView: [\Drupal\at_base\Twig\Filters\Views, render]

  # ---------------------
  # Contributed modules
  # ---------------------
  # Example: {{ variable|kpr }}
  kpr: kpr

  # Example: {{ variable|dsm }}
  dsm: dsm

  # ---------------------
  # at_base module
  # ---------------------
  # Example: {{ "%module:%id:%key"|at_config }}
  __at_config: [\Drupal\at_base\Twig\Filters\ATConfig, render]
  __cache: [\Drupal\at_base\Twig\Filters\Cache_Filter, render]
