twig_filters:
  # ---------------------
  # Core
  # ---------------------
  - [render, render]
  - [t, t]
  - [url, url]
  - [_filter_autop, _filter_autop]
  - [drupalBlock, [\Drupal\at_base\Twig\Filters\Block, render]]
  - [drupalEntity, [\Drupal\at_base\Twig\Filters\Entity, render]]
  - [drupalView, [\Drupal\at_base\Twig\Filters\Views, render]]

  # ---------------------
  # Contributed modules
  # ---------------------
  - [kpr, kpr]
  - [dsm, dsm]

  # ---------------------
  # at_base module
  # ---------------------
  # {{ "%module:%id:%key"|at_config }}
  - [at_config, [\Drupal\at_base\Twig\Filters\ATConfig, render]]
  - [cache, [\Drupal\at_base\Twig\Filters\Cache_Filter, render]]
